In [2]:
import tensorflow as tf
print(('your tensorflow version: {0}').format(tf.__version__))

your tensorflow version: 2.7.0


In [20]:
A= tf.constant([[4,3],
                [6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [4]:
V= tf.Variable([[3,1],
                [5,2]])
B= tf.constant([[7,8],
               [4,5]])
V
B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]], dtype=int32)>

In [5]:
V= tf.Variable([[3,1],
                [5,2]])
B= tf.constant([[7,8],
               [4,5]])
print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]], dtype=int32)>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]], dtype=int32)>

In [6]:
AB_concatenated= tf.concat(values=[A,B],axis=1) #axis=1 means concatenate horizontally
AB_concatenated


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]], dtype=int32)>

In [7]:
AB_concatenated= tf.concat(values=[A,B],axis=0) #axis=0 means bring all the columns down as rows 
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]], dtype=int32)>

In [10]:
tensor= tf.zeros(shape=[3,4],dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [12]:
tensor= tf.ones(shape=[3,4],dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [14]:
reshaped_tensor= tf.reshape(tensor=tensor,shape=[4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
tensor= tf.random.uniform(shape=[3,4])
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.21341693, 0.865211  , 0.6025853 , 0.06460822],
       [0.9703238 , 0.16219914, 0.5152004 , 0.87801456],
       [0.8163692 , 0.71791077, 0.16242683, 0.31400526]], dtype=float32)>

In [24]:
#typecast a tensor
tensor=tf.constant([[4.6,4.2],
                    [7.5,3.6],
                    [2.7,9.4],
                    [6.7,8.3]],dtype=tf.float32)
tensor_as_int= tf.cast(tensor,tf.int32)
print(tensor)
print(tensor_as_int)

tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.3]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [6 8]], shape=(4, 2), dtype=int32)


In [25]:
a= tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [4, 3, 9, 8]], dtype=int32)>

In [28]:
# MATRIX MULTIPLICATIONS
A= tf.constant([[5,8],
                [3,9]])
V= tf.constant([[4],
                [2]])
AV= tf.matmul(A,V)
AV

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]], dtype=int32)>

In [29]:
#ELEMENT-WISE MULTIPLICATION
AV= tf.multiply(A,V)
AV

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]], dtype=int32)>

In [31]:
#CREATING AN IDENTITY MATRIX
A= tf.constant([[4,9],
               [5,6],
               [1,8]])
rows,columns= A.shape
print("rows:",rows,"columns:",columns)

#MAKING IDENTITY MATRIX
A_identity= tf.eye(num_rows=rows,
                  num_columns=columns,
                  dtype=tf.int32)
A_identity

rows: 3 columns: 2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]], dtype=int32)>